# Tensorflow

In [19]:
import tensorflow as tf
import numpy as np


## 1. Tensorflow como numpy

In [2]:
# Tensores
tf.constant([[1., 2., 3., 4.],[1., 6., 2., 8.]])

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 2., 3., 4.],
       [1., 6., 2., 8.]], dtype=float32)>

In [3]:
tf.constant(1) # Escalar

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [5]:
tensor = tf.constant([[1., 2., 3., 4.],[1., 6., 2., 8.]])
print(tensor.shape)
print(tensor.dtype)

(2, 4)
<dtype: 'float32'>


Indexar

In [8]:
# Indexar
tensor[:,2:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 4.],
       [2., 8.]], dtype=float32)>

In [12]:
tensor[tf.newaxis,:,2:]

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[3., 4.],
        [2., 8.]]], dtype=float32)>

Operaciones matematicas

In [13]:
tensor + 2

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 3.,  4.,  5.,  6.],
       [ 3.,  8.,  4., 10.]], dtype=float32)>

In [14]:
tf.sqrt(tensor)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.99999994, 1.4142134 , 1.7320508 , 1.9999999 ],
       [0.99999994, 2.4494896 , 1.4142134 , 2.8284268 ]], dtype=float32)>

In [15]:
tensor @ tf.transpose(tensor)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 30.,  51.],
       [ 51., 105.]], dtype=float32)>

## 2. API de bajo nivel de Keras

In [17]:
from tensorflow import keras
Kb = keras.backend

In [18]:
Kb.constant([[1.,2.],[3.,4.]])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

## 3. Tensores

In [23]:
a = np.array([1., 2., 4.])
tensor = tf.constant(a)
tensor

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 4.])>

In [22]:
tensor.numpy()

array([1., 2., 4.])

Conversion de tipos

In [25]:
np.array(1) + np.array(3.)

4.0

In [26]:
tf.constant(1) + tf.constant(3.)

InvalidArgumentError: ignored

In [29]:
tf.constant(1, dtype=tf.float32) + tf.constant(3.)

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [30]:
tf.cast(tf.constant(1), tf.float32) + tf.constant(3.)

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

Variables

In [31]:
tensor = tf.constant([1., 2., 4.])
tensor

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 4.])>

In [32]:
tensor[1] = 5.

TypeError: ignored

In [33]:
variable = tf.Variable([1., 2., 4.])
variable

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 4.], dtype=float32)>

In [35]:
variable[1].assign(5.)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([1., 5., 4.], dtype=float32)>

Estructuras de datos

In [ ]:
tf.SparseTensor() # Representa tensores con muchos ceros
tf.TensorArray()